name: Update Booking Statuses

on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes

jobs:
  update_bookings:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -X POST https://<YOUR-SUPABASE-URL>/functions/v1/update_bookings \
          -H "Authorization: Bearer <YOUR_SERVICE_ROLE_KEY>"
